spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  mail:
    host: smtp.gmail.com
    port: 587
    username: koveevip@gmail.com
    password: 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
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8080

logging:
  level:
    org.springframework.mail: DEBUG
    org.springframework.web: DEBUG
